# Generated by Django 2.2.3 on 2019-07-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proboftheweek', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_explaination',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(max_length=1000),
        ),
    ]
