# Generated by Django 2.2.3 on 2019-08-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proboftheweek', '0002_auto_20190729_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='time',
            field=models.DateTimeField(verbose_name='time answered'),
        ),
    ]
