# Generated by Django 2.2.3 on 2019-07-21 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=1000)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('active_date', models.DateField()),
                ('answer', models.CharField(max_length=25)),
                ('answer_explaination', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=8)),
                ('answer_text', models.CharField(max_length=25)),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='time answered')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proboftheweek.Question')),
            ],
        ),
    ]
